#stages:
#  - build
#  - test

docker_build:
#  stage: build
  script:
    - echo pwd
    - cd backend
    - sh build_and_run_backend_and_database.sh
    - docker exec -it marssql bin/bash
    - mysql -u root -p
    - pass
    - use marsdb;
    - exit
    - exit
    - echo pwd

#postman_tests:
#  stage: test
#  image:
#    name: postman/newman_alpine33
#    entrypoint: [""]
#  script:
#    - newman -- version
#    - npm instal -g newman-reporter-html
#  artifacts:
#    when: always
#    paths:
#      - report.html