FROM openjdk:12-jdk as build
WORKDIR /workspace/app
 
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
 
COPY src src
RUN ./gradlew build

# entrypoint for docker container, this command is run automatically when the container is started, and it auto starts our app
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","build/libs/app-0.0.1-SNAPSHOT.jar", "--trace"]
